

export type Loan = {
  id: number;
  beneficiary_account: string;
  beneficiary_bank: string;
  customer__code: string;
  fee_ovd_cycle: number;
  fee_income: number;
  fee_num_cycle: number;
  fee_pay_cycle: number;
  fee_ovd_days: null | number;
  fee_penalty: null | number;
  fee_ovd: null | number;
  fee_next_date: string;
  fee_next_amount: number;
  fees: {
    code: string;
    name: string;
    type: number;
    value: number;
    method: number;
    type__code: string;
    method__code: string;
  }[];
  fee_collected: null | number;
  application__code: string;
  application: number;
  amount_given: number;
  penalty_ratio: number;
  product__install_cycle_days: null | number;
  product__type__code: string;
  product__base__code: string;
  penalty_amount: null | number;
  revenue: null | number;
  itr_next_amount: number;
  status__code: string;
  prin_ovd_days: null | number;
  itr_ovd_days: null | number;
  batch_date: string;
  due_date: string;
  due_days: number;
  product__currency__code: string;
  due_amount: number;
  prin_next_amount: number;
  itr_penalty: null | number;
  prin_penalty: null | number;
  itr_ovd_cycle: number;
  prin_ovd: null | number;
  itr_ovd: null | number;
  prin_ovd_cycle: number;
  prin_num_cycle: number;
  itr_num_cycle: number;
  prin_collected: null | number;
  itr_last_date: null | string;
  prin_last_date: null | string;
  itr_last_amount: null | number;
  prin_last_amount: null | number;
  itr_collected: null | number;
  itr_income: number;
  itr_pay_cycle: number;
  prin_pay_cycle: number;
  itr_next_date: string;
  prin_next_date: string;
  branch: number;
  branch__code: string;
  branch__name: string;
  product__type__name: string;
  prin_first_date: string;
  itr_first_date: string;
  prin_cycle_days: null | number;
  itr_cycle_days: null | number;
  dbm_entry__account: number;
  approver: number;
  approve_time: string;
  prin_pay_type: number;
  prin_pay_type__code: string;
  prin_pay_type__name: string;
  itr_pay_type: number;
  itr_pay_type__code: string;
  itr_pay_type__name: string;
  customer: number;
  customer__phone: string;
  customer__fullname: string;
  code: string;
  product: number;
  product__code: string;
  product__name: string;
  valid_from: string;
  valid_to: string;
  rate_info: string;
  disbursement: number;
  disbursement_local: number;
  outstanding: number;
  outstanding_local: number;
  principal: number;
  rate: number;
  status__name: string;
  dbm_entry: number;
  dbm_entry__code: string;
  creator__fullname: string;
  approver__fullname: string;
  update_time: string;
  create_time: string;
  ratio: number;
  status: number;
  creator: number;
  count_note: number;
  sms_count: number;
  file_count: number;
  collat_count: number;
};

export type Application = {
  id: number;
  payment_status__code: string;
  loanapp__disbursement: number;
  legal_type__code: string;
  fees: {
    code: string;
    name: string;
    type: number;
    value: number;
    amount: number;
    method: number;
    type__code: string;
    method__code: string;
    custom_amount?: number;
  }[];
  source: number;
  source__name: string;
  legal_type: number;
  status__index: number;
  appcntr__signature: number;
  appcntr__update_time: string;
  appcntr__user__fullname: null | string;
  approve_time: string;
  product: number;
  commission: null | number;
  customer: number;
  customer__code: string;
  product__type__en: string;
  update_time: string;
  updater__fullname: null | string;
  creator__fullname: null | string;
  approver: number;
  approver__fullname: string;
  product__type__name: string;
  product__type__code: string;
  product__category__name: string;
  product__category__code: string;
  product__commission: number;
  branch: number;
  status: number;
  status__name: string;
  status__en: string;
  branch__id: number;
  branch__name: string;
  branch__code: string;
  branch__type__en: string;
  branch__type__code: string;
  branch__type__id: number;
  branch__type__name: string;
  country__id: number;
  country__code: string;
  country__name: string;
  country__en: string;
  currency: number;
  currency__code: string;
  loan_amount: number;
  loan_term: number;
  code: string;
  fullname: string;
  phone: string;
  province: string;
  district: string;
  address: string;
  sex: number;
  sex__name: string;
  sex__en: string;
  issue_place: string;
  legal_type__name: string;
  legal_code: string;
  legal_type__en: string;
  issue_date: string;
  country: number;
  collaborator: null | number;
  collaborator__id: null | number;
  collaborator__user: null | number;
  collaborator__fullname: null | string;
  collaborator__code: null | string;
  create_time: string;
  salary_income: number;
  business_income: number;
  other_income: number;
  living_expense: number;
  loan_expense: number;
  other_expense: number;
  credit_fee: null | number;
  disbursement_fee: null | number;
  loan_fee: null | number;
  colateral_fee: null | number;
  note: string;
  commission_rate: null | number;
  payment_status: number;
  payment_info: null | string;
  history: number;
  ability: number;
  ability__name: string;
  ability__en: string;
  ability__code: string;
  doc_audit: number;
  onsite_audit: number;
  approve_amount: number;
  approve_term: number;
  loanapp: number;
  loanapp__code: string;
  purpose: number;
  purpose__code: string;
  purpose__name: string;
  purpose__en: string;
  purpose__index: number;
  loanapp__dbm_entry__date: string;
};

export type InternalEntry = {
    id: number;
    amount: number;
    type: number;
    date: string;
};





export type Statement = {
  id: string;
  loan_id: string;
  note: string;
  payment_date: string;
  principal_amount: number;
  interest_amount: number;
  management_fee: number;
  overdue_fee: number;
  settlement_fee: number;
  remaining_amount: number;
  vat_amount: number;
  total_amount: number;
  created_at?: any;
  updated_at?: any;
  created_by?: string;
}


export const loansData: Loan[] = [];
