export type Loan = {
  id: number;
  beneficiary_account: string;
  beneficiary_bank: string;
  customer__code: string;
  fee_ovd_cycle: number;
  fee_income: number;
  fee_num_cycle: number;
  fee_pay_cycle: number;
  fee_ovd_days: null | number;
  fee_penalty: null | number;
  fee_ovd: null | number;
  fee_next_date: string;
  fee_next_amount: number;
  fees: {
    code: string;
    name: string;
    type: number;
    value: number;
    method: number;
    type__code: string;
    method__code: string;
  }[];
  fee_collected: null | number;
  application__code: string;
  application: number;
  amount_given: number;
  penalty_ratio: number;
  product__install_cycle_days: null | number;
  product__type__code: string;
  product__base__code: string;
  penalty_amount: null | number;
  revenue: null | number;
  itr_next_amount: number;
  status__code: string;
  prin_ovd_days: null | number;
  itr_ovd_days: null | number;
  batch_date: string;
  due_date: string;
  due_days: number;
  product__currency__code: string;
  due_amount: number;
  prin_next_amount: number;
  itr_penalty: null | number;
  prin_penalty: null | number;
  itr_ovd_cycle: number;
  prin_ovd: null | number;
  itr_ovd: null | number;
  prin_ovd_cycle: number;
  prin_num_cycle: number;
  itr_num_cycle: number;
  prin_collected: null | number;
  itr_last_date: null | string;
  prin_last_date: null | string;
  itr_last_amount: null | number;
  prin_last_amount: null | number;
  itr_collected: null | number;
  itr_income: number;
  itr_pay_cycle: number;
  prin_pay_cycle: number;
  itr_next_date: string;
  prin_next_date: string;
  branch: number;
  branch__code: string;
  branch__name: string;
  product__type__name: string;
  prin_first_date: string;
  itr_first_date: string;
  prin_cycle_days: null | number;
  itr_cycle_days: null | number;
  dbm_entry__account: number;
  approver: number;
  approve_time: string;
  prin_pay_type: number;
  prin_pay_type__code: string;
  prin_pay_type__name: string;
  itr_pay_type: number;
  itr_pay_type__code: string;
  itr_pay_type__name: string;
  customer: number;
  customer__phone: string;
  customer__fullname: string;
  code: string;
  product: number;
  product__code: string;
  product__name: string;
  valid_from: string;
  valid_to: string;
  rate_info: string;
  disbursement: number;
  disbursement_local: number;
  outstanding: number;
  outstanding_local: number;
  principal: number;
  rate: number;
  status__name: string;
  dbm_entry: number;
  dbm_entry__code: string;
  creator__fullname: string;
  approver__fullname: string;
  update_time: string;
  create_time: string;
  ratio: number;
  status: number;
  creator: number;
  count_note: number;
  sms_count: number;
  file_count: number;
  collat_count: number;
};

export const loansData: Loan[] = [];
